### ISSUE TITLE
Temporarily unavailable

### ISSUE THREAD

**Issue by roseha177** [tim-hub/canva-app-simple-qr-code#2]
App has been down for over 48 hours. Please fix it

**Comment by tim-hub** [comment]
Thanks for the feedback.

Would you like to provide more detail such as screenshot/recording?


I tried on my side, it worked as expected.

**Comment by tim-hub** [comment]
![image](https://github.com/tim-hub/canva-app-simple-qr-code/assets/2884320/17f269e6-63fb-4d41-912b-b89a100a0eb4)
