### ISSUE TITLE
Canva app simple qr

### ISSUE THREAD

**Issue by marap42** [tim-hub/canva-app-simple-qr-code#6]
Hi, this app is very useful.. thank you.. but now I can’t use this app.. the application warns that it is not working.. please check your app.. we would like to use this app.. thanks best regards

**Comment by tim-hub** [comment]
Very sadly to say, this app was removed by Canva, I tried to get it back, but the support team did not really help it out in the end.

https://github.com/tim-hub/canva-app-simple-qr-code/issues/5
