### ISSUE TITLE
Canva Simple QR Code stopped working without notice

### ISSUE THREAD

**Issue by Press4Ward** [tim-hub/canva-app-simple-qr-code#7]
The Canva Simple QR Code stopped working. Had to change ALL of my client's marketing that had a QR code that I generated. I did not receive any type of notification from Canva that the App was experiencing issues or wasn't available. As a paying customer of Canva, they have to do better.

<img width="432" alt="Screenshot 2024-09-03 at 11 54 39 AM" src="https://github.com/user-attachments/assets/a2d609c2-a6f7-428c-b7a8-c077e0a6f682">

**Comment by tim-hub** [comment]
Very sadly to say, this app was removed by Canva, I tried to get it back, but the support team did not really help it out in the end. 

https://github.com/tim-hub/canva-app-simple-qr-code/issues/5
